### ISSUE TITLE
ionic upload -> Error 500

### ISSUE THREAD

**Issue by casper60** [driftyco/ionic-push-issues#1]
Everytime I try to upload my projects, I get a server error 500.
When I open Ionic View, I also get a server error 500.

$ ionic upload

Uploading app...
Server Error (500) :( (CLI v1.3.16)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.16
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1

**Comment by mlynch** [comment]
Did you manually set app_id in ionic.project? If so clear it out and try again.

Co-founder, http://drifty.com/




On Mon, Mar 23, 2015 at 10:26 AM -0700, "Casper Knudsen" <notifications@github.com> wrote:












Everytime I try to upload my projects, I get a server error 500.

When I open Ionic View, I also get a server error 500.



$ ionic upload



Uploading app...

Server Error (500) :( (CLI v1.3.16)



Your system information:



OS: Mac OS X Yosemite

Node Version: v0.10.33

Cordova CLI: 4.3.0

Ionic CLI Version: 1.3.16

Xcode version: Xcode 6.2 Build version 6C131e 

ios-sim version: 3.1.1

**Comment by casper60** [comment]
I did not set the app_id. My ionic.config looks like this:

{
	"name": "Røgeovnen",
	"app_id": ""
}

I changed the "ø" character to an "o", and that fixed the issue. Thanks for your time.

**Comment by skarppion101** [comment]
I've also noticed that when the name of your app contains Russian characters it throws the same error
