### ISSUE TITLE
Push sent according to message status, but doesn't show on device

### ISSUE THREAD

**Issue by spivotron** [driftyco/ionic-push-issues#12]
I am able to register device tokens, identify and register users for iOS but now sending pushes doesn't work although their statuses indicate they have been sent successfully.

For instance I've sent a push to a device (my own).  It never displays on my device but here's the message status:

![](http://cdn.discourse.org/business/uploads/ionicframework/original/2X/7/70a12ffc6cfeac1e9d5480257e653c916fc99a47.png)
I also have the following in my run function in my app.js:
<code>$rootScope.$on('$cordovaPush:notificationReceived', function (event, notification) {
				if (notification.alert) {
					navigator.notification.alert(notification.alert);
				}
			});</code>
Any idea what could be happening here?  
Thank you.

**Comment by Fuiste** [comment]
This issue usually occurs when your push is sent to GCM or APNS, but fails on their end for some reason (usually a certificate error or sandbox/production mismatch from APNS).

We need to do a better job of surfacing this information, but for the moment I'd go over your generated certificates and ensure that they're all correct.

We usually try to help out in [Gitter](https://gitter.im/driftyco/ionic-io-testers) as we are able, as well.

**Comment by gimox** [comment]
same problem here +

**Comment by gimox** [comment]
resolved removing all certificates dev and prod and adding  only the dev cert.
