### ISSUE TITLE
Custom sound not working

### ISSUE THREAD

**Issue by Elyahou** [driftyco/ionic-push-issues#17]
I am sending something like this:

````
"android": {
       "sound": "customsound"
     }
````

and put a customsound.mp3 in the android/res/raw folder.

But ionic.io are changing my sound file name to testsound so that I am receiving in the client 

````
sound: "testsound"
````

It is working only if i am renaming my sound file to testsound.mp3. But then I cannot use diferent sound file for diferent notifications.

**Comment by JoeKool** [comment]
We can't use ionic push because of this issue. Is anyone looking at the issue tracker because this should be extremely easy to fix? Not to mention such a bug should not have made this far.

**Comment by Fuiste** [comment]
A fix has been published to address this issue, sorry for the delay on that.  

We had been testing using:

```
"android": {
  "payload": {
    "sound": "foo"
  }
}
``` 

and must have missed this.

In the future, you can find the repo's we're more closely monitoring [here](http://docs.ionic.io/v1.0/docs/issues).
