### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by benrondeau** [driftyco/ionic-push-issues#4]
Got the push service to work. Good stuff guys!

I want to make a recommendation on improving the docs. On the [Sending Push](http://docs.ionic.io/push/send) page, it asks you to input your 'Private' API Key to authenticate with the server, but in the App config dashboard, it is referred to ask the 'secret' key. It is confusing which key is being referred to and took some time to figure out which API key to use.

Overall good stuff though. Look forward to seeing an API interface on the Push console page instead of only the REST API option.

**Comment by jason-engage** [comment]
I'd love to see these docs! Shows a 'Not Yet Active' notice. Is there an ETA?

**Comment by mlynch** [comment]
Hey Jason, just navigate here: http://docs.ionic.io/ and you can see all
the push docs!

On Mon, Apr 20, 2015 at 3:14 PM, jason-engage <notifications@github.com>
wrote:

> I'd love to see these docs! Shows a 'Not Yet Active' notice. Is there an
> ETA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-push-issues/issues/4#issuecomment-94557498>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by jason-engage** [comment]
Whaat, you guys are fast! Congrats on your recent round of funding.

**Comment by mlynch** [comment]
Thanks :)

On Mon, Apr 20, 2015 at 3:18 PM, jason-engage <notifications@github.com>
wrote:

> Whaat, you guys are fast! Congrats on your recent round of funding.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-push-issues/issues/4#issuecomment-94558243>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/
