### ISSUE TITLE
Only able to send/receive alerts, $ionicPush: No device, sending alert instead.  Angular version 1.2.28, iOS platform

### ISSUE THREAD

**Issue by spivotron** [driftyco/ionic-push-issues#7]
Hello,
I am trying to implement push notifications using $ionicPush.  I have followed the instructions [here] (http://docs.ionic.io/v1.0/docs/push-from-scratch).  In XCode, my device token (guid) is generated: REGISTERED_DEV_MODE DEV-2ddbd4f2-e7e8-46b4-b150-878d6515d68a but when I try to send a push notification through the Ionic dashboard, I only receive an alert, not a push notification.  

As an aside, I got [this](https://github.com/driftyco/ionic-push-issues/issues/5) error when I first installed the service and managed to find a work around, but maybe that isn't helping my issue this time.  

Thank you!

**Comment by ohh2ahh** [comment]
This is the intended behavior.

> The device tokens generated for dev pushes only function for two hours, and only while the app is open.
– http://docs.ionic.io/v1.0/docs/push-development-mode

You have to set up Apple Push Notification Service in order to use real notifications on iOS ([instructions](http://docs.ionic.io/v1.0/docs/push-ios-setup)).
